config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/sign_up', to: 'users#new', as: :sign_up
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/sessions', to: 'sessions#new'
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only: [:new, :create]  
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions do 
    put "like", to: "questions#upvote"
    put "dislike", to: "questions#downvote"
    put "unvote", to: "questions#unvote"
    post "create_question_comment", to: "comments#question_comments"
    resources :comments, module: :questions
  end
  resources :comments do 
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
    put "unvote", to: "comments#unvote"
  end
  post 'comments/:id/reply', to: 'comments#reply', as: :reply

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

class Question < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_votable
  is_impressionable
  
  belongs_to :user
  has_many :comments, as: :commentable
  
  
  validates :title, presence: true
  validates :description, presence: true
  validates :user, presence: true

  def self.search(word: nil)
    with_word(word)
    .with_order
  end
  scope :with_word, proc { |word|
    if word.present?
      where("title like ?  OR description LIKE ? ", "%#{word}%", "%#{word}%")
    end
  }
  scope :with_order, -> { order('created_at DESC') }
  
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Question.friendly.find(params[:question_id])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :set_question_for_votes, only: [:upvote, :downvote, :unvote]
  impressionist actions: [:show]
  
  def index
    @questions = Question.with_word(params[:question]).with_order
  end

  def show
    @question = Question.friendly.find(params[:id]) 
    @question_comments = Comment.where(commentable_type: "questionComment", commentable_id: @question.id)
    impressionist(@question)
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def upvote
    @question.upvote_by current_user
    redirect_to question_path(@question)
  end
  def unvote
    @question.unvote_by current_user
    redirect_to question_path(@question)    
  end
  def downvote
    @question.downvote_by current_user
    redirect_to question_path(@question)
  end
  def destroy
    if @question.destroy
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  private
  def set_question_for_votes
    @question = Question.friendly.find(params[:question_id])
  end
  def set_question
    @question = Question.friendly.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_title
    @question.new_record? ? "Nueva Pregunta" : "Editar Pregunta"
  end
  def show_search_question
    controller.action_name == "index" || controller.action_name == "show"
  end
  def votes_prom(upvotes, downvotes)
    upvotes - downvotes
  end
  def last_qc(qc, question_comments)
    unless question_comments.last == qc
      '<hr>'.html_safe
    else
      ''
    end
  end

end

app/views/questions/_form.html.erb
<div class="question-form form-container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center"><%= form_title %></h1>
          <% if @question.errors.any? %>
            <div class="alert alert-danger">
              <ul>
              <% @question.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= form_for @question do |f| %>
            <div class="form-group">
              <%= f.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el titulo de la pregunta" %>
            </div>
            <div class="form-group">
              <%= f.text_area :description, class: "form-control input-lg text-area", placeholder: "Ingresa la descripción de la pregunta" %>
            </div>
            <div>
              <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var simplemde = new SimpleMDE({
    element: $(".text-area")[0],
    placeholder: "Ingresa la descripción de la pregunta",
    renderingConfig: {
		singleLineBreaks: false,
		codeSyntaxHighlighting: true,
	  }
  });
</script>

app/views/questions/_votes.html.erb
<div class="vote-box">
  <% if current_user%>
    <% unless current_user.voted_for? @question%>
      <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, question_like_path(@question), method: :put %> </div>
    <% else %>
      <% unless current_user.voted_up_on? @question%>                
        <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, question_like_path(@question), method: :put %> </div>
        <div class="votes-counter" ><%= votes_prom(@question.get_upvotes.size, @question.get_downvotes.size) %></div>                
        <div><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, question_unvote_path(@question), method: :put, class: 'text-muted' %> </div>              
      <% else %>      
        <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, question_unvote_path(@question), method: :put, class: 'text-muted' %> </div>      
        <div class="votes-counter" ><%= votes_prom(@question.get_upvotes.size, @question.get_downvotes.size) %></div>        
        <div><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, question_dislike_path(@question), method: :put, class: 'text-danger'  %></div>
      <% end %>
    <% end %>
    <% unless current_user.voted_for? @question%>
      <div class="votes-counter" ><%= votes_prom(@question.get_upvotes.size, @question.get_downvotes.size) %></div>        
      <div ><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, question_dislike_path(@question), method: :put, class: 'text-danger' %></div>      
    <% end %>
  <% else %>
    <div><button class="btn btn-link disabled" data-toggle="tooltip" data-placement="right" title="Inicia sesión para votar"><i class="material-icons">thumb_up</i></a></div>
    <div class="votes-counter" ><%= votes_prom(@question.get_upvotes.size, @question.get_downvotes.size) %></div>
    <div><button class="btn btn-link disabled" data-toggle="tooltip" data-placement="right" title="Inicia sesión para votar"><i class="material-icons">thumb_down</i></a></div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%= render 'form'%>

app/views/questions/index.html.erb
<div class="questions form-container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <% @questions.each do |question| %>
        <div class="card">
          <div class="card-body">
            <h2 class="title"><%= link_to  question.title, question_path(question) %></h2>
            <span class="user">Preguntó: <strong><%= question.user.email %></strong></span> <br>
            <span class="date">preguntado hace: <%= time_ago_in_words(question.created_at) %></span>
            <hr>
            <div class="box-container">
              <div class="box">
                <span><%= question.votes_for.size %></span>
                <small>Votos</small>
              </div>
              <div class="box">
                <span><%= question.comments.count %></span>
                <small>Respuestas</small>
              </div>
              <div class="box">
                <span><%= question.impressionist_count %></span>
                <small>Visto</small>
              </div>
            </div>
          </div>
        </div> 
        <br>
      <% end %>      
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form'%>

app/views/questions/show.html.erb
<div class="question form-container">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%=type%> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong> <%= message %> </strong>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card">
        <div class="card-body">
          <h2 class="title text-center"><%= @question.title %></h2>
          <%=markdown(@question.description)%>
          <hr>
          <% if @question_comments.count > 0 %>
            <div class="question_comments align-right">
              <% @question_comments.each do |qc| %>
                <div>
                  <span><%= qc.body %> - <strong><%= qc.user.email%></strong> <span>hace <%= time_ago_in_words(qc.created_at) %></span> </span>  
                </div>
                <%= last_qc(qc, @question_comments) %>
              <% end %>              
            </div>
          <% end %>
          <%if question_owner%>
            <div class="actions text-center">
              <%= link_to  "Editar", edit_question_path(@question), class: 'btn btn-outline-primary btn-sm' %>
              <%= link_to  "Borrar", question_path(@question), method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-outline-primary btn-sm' %>
            </div>
          <% end %>
          <div class="data">
            <span class="user">Preguntó: <strong><%= @question.user.email %></strong></span>
            |
            <span class="date">preguntado: <%= time_ago_in_words(@question.created_at) %></span>
            <%= render 'votes' %>
          </div>
        </div>
      </div>
      <hr>
      <div class="comments">
        <% if current_user %>
          <div class="text-right">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createReplyModal" >Responder</button>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createCommentModal" >Comentar</button>
            </div>
          </div>
        <% end %>
        <%= render partial: 'comments/comments', locals: {commentable: @question} %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="createReplyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Nueva Respuesta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render partial: "comments/form", locals: {commentable: @question} %>              
    </div>
  </div>
</div>

<div class="modal fade" id="createCommentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Comentario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="question-comment-form" accept-charset="UTF-8" method="post" action="/questions/<%=@question.id%>/create_question_comment" >
          <div class="modal-body">
            <input name="utf8" type="hidden" value="✓">
            <input type="hidden" name="authenticity_token" value="/9znzBoOltR9YeYvvY4JTH0lnK8pOdjviL1zSHR/HorUvKzVj6rmCf25KuJKcmsKJuGSrLeddGDoKZz68vrKAA==">
            <input type="hidden" name="qp[question_id]" id="id" value="<%= @question.id%>">
            <input type="hidden" name="qp[commentable_type]" value="questionComment">
            <div class="form-group">
              <label for="message-text" class="col-form-label">Mensaje:</label>
              <textarea class="form-control" id="body" name="qp[body]"></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <input type="submit" class="btn btn-primary" value="Comentar" />
          </div>
        </form>    
      </div>
    </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('pre code').each(function(i, block) {
      hljs.highlightBlock(block);
    })
  })
</script>