config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/sign_up', to: 'users#new', as: :sign_up
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/sessions', to: 'sessions#new'
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only: [:new, :create]  
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions do 
    put "like", to: "questions#upvote"
    put "dislike", to: "questions#downvote"
    put "unvote", to: "questions#unvote"
    post "create_question_comment", to: "comments#question_comments"
    resources :comments, module: :questions
  end
  resources :comments do 
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
    put "unvote", to: "comments#unvote"
  end
  post 'comments/:id/reply', to: 'comments#reply', as: :reply

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  commentable_type :string
#  commentable_id   :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#  body             :string
#

class Comment < ApplicationRecord
  acts_as_votable  
  
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  belongs_to :commentable,  class_name: "Comment" #-> requires "parent_id" column
  has_many   :replies, class_name: "Comment", foreign_key: :commentable_id, dependent: :destroy

  validates :body, presence: true  
  validates :user, presence: true  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:reply]
  before_action :set_comment_for_votes, only: [:upvote, :downvote, :unvote]
  
  def create
    @comment = @commentable.comments.new(comment_params)
    unless @comment.save
      flash[:danger] = "La respuesta  no puede estar vacio"
    end
    redirect_to @commentable
  end

  def reply
    reply = @comment.replies.new(reply_params)
    unless reply.save
      flash[:danger] = "El comentario no puede estar vacio"
    end
    redirect_to question_path(@comment.commentable_id) 
  end
  
  def question_comments
    comment = Comment.new(question_comments_params)
    comment.commentable_id = params[:question_id]
    unless comment.save
      flash[:danger] = "La respuesta  no puede estar vacio"
    end
    redirect_to question_path(comment.commentable_id) 
  end

  def upvote
    @comment.upvote_by current_user
    redirect_to question_path(@comment.commentable_id)
  end
  def unvote
    @comment.unvote_by current_user
    redirect_to question_path(@comment.commentable_id)    
  end
  def downvote
    @comment.downvote_by current_user
    redirect_to question_path(@comment.commentable_id)
  end


  private

  def set_comment
    @comment = Comment.find(params[:id])    
  end

  def set_comment_for_votes
    @comment = Comment.find(params[:comment_id])
  end


  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end

  def reply_params
    params.require(:Reply).permit(:body, :commentable_type).merge(user: current_user)
  end
  def question_comments_params
    params.require(:qp).permit(:body, :commentable_type).merge(user: current_user)
  end

end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Question.friendly.find(params[:question_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def type_comment(type)
    return type === 'Comment'
  end
end

app/views/comments/_comments.html.erb
<% if commentable.comments.count > 0%>
  <h3 class="text-center">Respuestas</h3>
<% end %>
<% commentable.comments.each do |comment| %>
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-2">
      <div class="vote-container"><%= render 'comments/votes', comment: comment %></div>      
    </div>
    <div class="col-sm-8">
      <div class="lead"><%=markdown(comment.body)%></div>                    
    </div>
    <div class="col-sm-2 text-center">
      <% if current_user %>
        <button id="reply-<%=comment.id%>" type="button" class="btn btn-primary" data-toggle="modal" data-target="#createReply" data-whatever="<%=comment.id%>">Comentar</button>
      <% end %>
    </div>
  </div>
  <hr class="my-4">
  <div class="data">
    <span class="user">Preguntó: <strong><%= comment.user.email %></strong></span>
    |
    <span class="date">preguntado hace: <%= time_ago_in_words(comment.created_at) %></span>
  </div>
  <% if !comment.replies.blank? %>
    <div class="replies align-right">
      <%comment.replies.each do |reply|%>
        <% if type_comment reply.commentable_type %>
          <div>
            <span><%=reply.body%> - <strong><%=reply.user.email%></strong> <span>hace <%= time_ago_in_words(reply.created_at) %></span> </span>  
          </div>
          <%= last_reply(reply, comment.replies) %>
        <% end %>
      <%end%>        
    </div>
  <% end %>
</div>
<% end %>

<div class="modal fade" id="createReply" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Comentario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="reply-form" accept-charset="UTF-8" method="post" >
        <div class="modal-body">
          <input name="utf8" type="hidden" value="✓">
          <input type="hidden" name="authenticity_token" value="/9znzBoOltR9YeYvvY4JTH0lnK8pOdjviL1zSHR/HorUvKzVj6rmCf25KuJKcmsKJuGSrLeddGDoKZz68vrKAA==">
          <input type="hidden" name="Reply[comment_id]" id="comment_id">
          <input type="hidden" name="Reply[commentable_type]" value="Comment">
          <div class="form-group">
            <label for="message-text" class="col-form-label">Mensaje:</label>
            <textarea class="form-control" id="body" name="Reply[body]"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <input type="submit" class="btn btn-primary" value="Comentar" />
        </div>
      </form>    
    </div>
  </div>
</div>
<script>
    $('#createReply').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var id = button.data('whatever') // Extract info from data-* attributes
      $('#reply-form').attr('action', '/comments/' + id + '/reply')
      $('#comment_id').val(id)
    })
    $('[data-toggle="tooltip"]').tooltip()
</script>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do  |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.text_area :body, class: "form-comtrol text-area", placeholder: 'Comentar ....'%>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <%= f.submit 'Responder', class: 'btn btn-primary' %>
  </div>
<% end %>
<script>
    var simplemde = new SimpleMDE({
      element: $(".text-area")[0],
      placeholder: "Responder....",
      renderingConfig: {
      singleLineBreaks: false,
      codeSyntaxHighlighting: true
      }
    });
  </script>

app/views/comments/_votes.html.erb
<div class="vote-box">
  <% if current_user%>
    <% unless current_user.voted_for? comment%>
      <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, comment_like_path(comment), method: :put %> </div>
    <% else %>
      <% unless current_user.voted_up_on? comment%>
        <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, comment_like_path(comment), method: :put %> </div>
        <div class="votes-counter" ><%= votes_prom(comment.get_upvotes.size, comment.get_downvotes.size) %></div>
        <div><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, comment_unvote_path(comment), method: :put, class: 'text-muted' %> </div>
      <% else %>
        <div><%= link_to '<i class="material-icons">thumb_up</i>'.html_safe, comment_unvote_path(comment), method: :put, class: 'text-muted' %> </div>
        <div class="votes-counter" ><%= votes_prom(comment.get_upvotes.size, comment.get_downvotes.size) %></div>
        <div><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, comment_dislike_path(comment), method: :put, class: 'text-danger' %></div>
      <% end %>
    <% end %>
    <% unless current_user.voted_for? comment%>
      <div class="votes-counter" ><%= votes_prom(comment.get_upvotes.size, comment.get_downvotes.size) %></div>
      <div ><%= link_to '<i class="material-icons">thumb_down</i>'.html_safe, comment_dislike_path(comment), method: :put, class: 'text-danger' %></div>
    <% end %>
  <% else %>
    <div><button class="btn btn-link disabled" data-toggle="tooltip" data-placement="right" title="Inicia sesión para votar" ><i class="material-icons">thumb_up</i></button></div>
    <div class="votes-counter" ><%= votes_prom(comment.get_upvotes.size, comment.get_downvotes.size) %></div>
    <div><button href="javascript:void(0);" class="btn btn-link disabled" data-toggle="tooltip" data-placement="right" title="Inicia sesión para votar"><i class="material-icons">thumb_down</i></button></div>
  <% end %>
</div>