config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/sign_up', to: 'users#new', as: :sign_up
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/sessions', to: 'sessions#new'
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only: [:new, :create]  
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions do 
    put "like", to: "questions#upvote"
    put "dislike", to: "questions#downvote"
    put "unvote", to: "questions#unvote"
    post "create_question_comment", to: "comments#question_comments"
    resources :comments, module: :questions
  end
  resources :comments do 
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
    put "unvote", to: "comments#unvote"
  end
  post 'comments/:id/reply', to: 'comments#reply', as: :reply

end

app/views/layouts/_nav.html.erb
<div class="nav-bar">
  <nav class="navbar navbar-expand-lg navbar-light container">
    <%= link_to  "OverFlow", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if show_search_question%>
          <%= form_tag questions_path, class: "form-inline my-2 my-lg-0", method: :get do %>
            <div class="input-group">
              <%= text_field_tag :question, params[:question], class: "form-control", placeholder: "Buscar pregunta..." %>
              <span class="input-group-btn">
                <%= submit_tag "Buscar", name: nil, class: "btn btn-primary" %>
              </span>
            </div>
          <% end %>
        <% end %>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"><%= link_to 'Preguntar', new_question_path , class:'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Salir', log_out_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item" ><%= link_to 'Registrarse', sign_up_path, class:'nav-link' %></li>
          <li class ="nav-item"><%= link_to 'Iniciar sesión', log_in_path, class:'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askflow</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/highlight.js/latest/styles/github.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="https://cdn.jsdelivr.net/highlight.js/latest/highlight.min.js"></script>
    <link rel="stylesheet"
    href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
    <script>hljs.initHighlightingOnLoad();</script>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <div class="container">
     <%=yield%>
    </div>
    <%=yield :javascript%>
  </body>
</html>